EFTest/EFTest/Models/Course.cs
using System.ComponentModel.DataAnnotations;
namespace EFTest.Models
{
    public class Course
    {
        [Key]
        public int ID { get; set; }
        public string? Name { get; set; }
        public List<StudentCourses>? StudentCourses { get; set; }
    }
}

EFTest/EFTest/Models/ErrorViewModel.cs
namespace EFTest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EFTest/EFTest/Models/Student.cs
using System.ComponentModel.DataAnnotations;
namespace EFTest.Models
{
    public class Student
    {
        [Key]
        public int ID { get; set; }
        public string? LastName { get; set; }
        public string? FirstMidName { get; set; }
        public DateTime EnrollmentDate { get; set; }
        public List <StudentCourses>? StudentCourses { get; set; }
    }
}

EFTest/EFTest/Models/StudentCourses.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace EFTest.Models
{
    [PrimaryKey(nameof(StudentID), nameof(CourseID))]
    public class StudentCourses
    {
        public int StudentID { get; set; }
        // Property Navigation
        [ForeignKey(nameof(StudentID))]
        public Student? Student { get; set; }
        public int CourseID { get; set; }
        [ForeignKey(nameof(CourseID))]
        public Course? Course { get; set; }
        public DateTime SignDate { get; set; }
        public DateTime? CancelDate { get; set; }

    }
}

EFTest/EFTest/ViewModels/StudentCourses/StudentCoursesViewModel.cs
using EFTest.Models;

namespace EFTest.ViewModels.StudentCourses
{
    public class StudentCoursesViewModel
    {
        public int StudentId { get; set; }
        public List<Student>? Students { get; set; } = [];
        public List<SelectedCourses>? Courses { get; set; } = [];
        public string? StudentName { get; set; }

        public void SetCourses(List<Course> courses)
        {
            Courses = [.. courses.Select(
                c => new SelectedCourses {
                    Id = c.ID,
                    Name = c.Name!,
                    IsSelected = false
                }
            )];
        }
    }

    public class SelectedCourses
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public bool IsSelected { get; set; }
    }
}

EFTest/EFTest/Controllers/DropDownListController.cs
using Microsoft.AspNetCore.Mvc;

namespace EFTest.Controllers
{
    public class DropDownListController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EFTest/EFTest/Controllers/StudentCoursesController.cs
using EFTest.Models;
using EFTest.Repository;
using EFTest.ViewModels.StudentCourses;
using Microsoft.AspNetCore.Mvc;

namespace EFTest.Controllers
{
    public class StudentCoursesController : Controller
    {
        private readonly ICourseRepository _courseRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly IStudentCoursesRepository _studentCoursesRepository;

        public StudentCoursesController
            (ILogger<CourseController> logger,
            ICourseRepository courseRepository,
            IStudentRepository studentRepository,
            IStudentCoursesRepository studentCoursesRepository
        )
        {
            _courseRepository = courseRepository;
            _studentRepository = studentRepository;
            _studentCoursesRepository = studentCoursesRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var data = await _studentRepository.GetAll();

            return View(data);
        }

        [HttpGet]

        public async Task<IActionResult> Create()
        {
            var viewModel = new StudentCoursesViewModel();

            viewModel.Students = await _studentRepository.GetAllNotEnrolled();

            viewModel.SetCourses(await _courseRepository.GetAll());

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(StudentCoursesViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                foreach (var c in viewModel.Courses)
                {
                    if(c.IsSelected)
                    {
                        await _studentCoursesRepository.Create(
                            new Models.StudentCourses {
                                StudentID = viewModel.StudentId,
                                CourseID = c.Id,
                                SignDate = DateTime.Now
                            }
                        );
                    }
                }

                return RedirectToAction("Index");
            }
            return View(viewModel);

        }

        [HttpGet]
        public async Task<IActionResult> Update(int studentId)
        {
            var allCourses = await _courseRepository.GetAll();
            var enrolledCourses = await _studentCoursesRepository.GetByStudentId(studentId);

            var student = await _studentRepository.GetById(studentId);

            var viewModel = new StudentCoursesViewModel
            {
                StudentId = studentId,
                StudentName = student != null ? $"{student.FirstMidName} {student.LastName}" : "",
                Students = null
            };
            viewModel.SetCourses(allCourses);

            foreach (var c in viewModel.Courses)
            {
                // Marque como selecionado se o estudante está matriculado e não cancelado
                c.IsSelected = enrolledCourses.Any(
                    sc => sc != null && sc.CourseID == c.Id && sc.CancelDate == null
                );
            }
            return View(viewModel);

        }

        [HttpPost]

        public async Task<IActionResult> Update(StudentCoursesViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var enrolledCourses = await _studentCoursesRepository.GetByStudentId(viewModel.StudentId);

                foreach (var c in viewModel.Courses)
                {
                    var isEnrolled = enrolledCourses.FirstOrDefault(
                        sc => sc != null && 
                        sc.CourseID == c.Id &&
                        sc.CancelDate == null
                    );

                    if (c.IsSelected)
                    {
                        if (isEnrolled == null)
                        {
                            await _studentCoursesRepository.Create(
                                new Models.StudentCourses
                                {
                                    StudentID = viewModel.StudentId,
                                    CourseID = c.Id,
                                    SignDate = DateTime.Now
                                }
                            );
                        }
                    }
                    else
                    {
                        if (isEnrolled != null)
                        {
                            isEnrolled.CancelDate = DateTime.Now;
                            await _studentCoursesRepository.Update(isEnrolled);
                        }
                    }
                }
                return RedirectToAction("Index");
            }
            viewModel.SetCourses(await _courseRepository.GetAll());
            return View(viewModel);
        }
    }
}

EFTest/EFTest/Views/Course/Create.cshtml
@model EFTest.Models.Course

@{
    ViewData["Title"] = "Curso";
}

<h1>Create</h1>
<h4>Course</h4>
<hr />

<div class="row">

    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly"
                 class="text-danger"></div>

            <div class="form-group">
                <label class="control-label">Nome</label>
                <input asp-for="Name"
                       class="form-control" />
                <span asp-validation-for="Name"
                      class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar"
                       class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>

EFTest/EFTest/Views/Course/Index.cshtml
@model ICollection<EFTest.Models.Course>

@{
    ViewData["Title"] = "Cursos";
}

<div class="text-center">
    <h1 class="display-4">
        @Model.Count cursos.
    </h1>

    <a asp-controller="Course" asp-action="Create" class="btn btn-primary">
        Novo Curso
    </a>
    <table class="table table-responsive table-hover table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Excluir</th>
                <th>Editar</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var s in Model)
            {
                <tr>
                    <td>@s.ID</td>
                    <td>@s.Name</td>
                    <td>
                        <form asp-controller="Course" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@s.ID" />
                            <button type="submit" class="btn btn-danger"
                                    onclick="return confirm('Confirma a exclusão do estudante?');">
                                Excluir
                            </button>
                        </form>
                    </td>
                    <td>
                        <a asp-action="Update" asp-route-id="@s.ID" class="btn btn-sm">
                            Editar
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

EFTest/EFTest/Views/Course/Update.cshtml
@model EFTest.Models.Course

@{
    ViewData["Title"] = "Curso";
}

<h1>Update</h1>
<h4>Course</h4>
<hr />

<div class="row">

    <div class="col-md-4">
        <form asp-action="Update" asp-route-id="@Model.ID">
            <div asp-validation-summary="ModelOnly"
                 class="text-danger"></div>

            <input type="hidden" asp-for="ID" />

            <div class="form-group">
                <label class="control-label">Nome</label>
                <input asp-for="Name"
                       class="form-control" />
                <span asp-validation-for="Name"
                      class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar Alterações"
                       class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>

EFTest/EFTest/Views/Home/Create.cshtml
@model EFTest.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h4>Student</h4>
<hr />

<div class="row">

    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" 
                class="text-danger"></div>

            <div class="form-group">
                <label class="control-label">Nome</label>
                <input asp-for="FirstMidName"
                    class="form-control" />
                <span asp-validation-for="FirstMidName"
                    class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Sobrenome</label>
                <input asp-for="LastName"
                       class="form-control" />
                <span asp-validation-for="LastName"
                      class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Data de Matrícula</label>
                <input asp-for="EnrollmentDate"
                       class="form-control" />
                <span asp-validation-for="EnrollmentDate"
                      class="text-danger"></span>
            </div>

            

            <div class="form-group">
                <input type="submit" value="Salvar"
                       class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>

EFTest/EFTest/Views/Home/Index.cshtml
@model ICollection<EFTest.Models.Student>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">
        @Model.Count estudantes.
    </h1>

    <a asp-controller="Home" asp-action="Create" class="btn btn-primary">
        Novo Estudante
    </a>
    <table class="table table-responsive table-hover table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Sobrenome</th>
                <th>Data matrícula</th>
                <th>Excluir</th>
                <th>Editar</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var s in Model)
            {
                <tr>
                    <td>@s.ID</td>
                    <td>@s.FirstMidName</td>
                    <td>@s.LastName</td>
                    <td>@s.EnrollmentDate.ToShortDateString()</td>
                    <td>
                        <form asp-controller="Home" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@s.ID" />
                            <button type="submit" class="btn btn-danger"
                                onclick="return confirm('Confirma a exclusão do estudante?');">
                                Excluir
                            </button>
                        </form>
                    </td>
                    <td>
                        <a asp-action="Update" asp-route-id="@s.ID" class="btn btn-sm">
                            Editar
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

EFTest/EFTest/Views/Home/Update.cshtml
@model EFTest.Models.Student

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>
<h4>Student</h4>
<hr />

<div class="row">

    <div class="col-md-4">
        <form asp-action="Update" asp-route-id="@Model.ID">
            <div asp-validation-summary="ModelOnly" 
                class="text-danger"></div>

            <input type="hidden" asp-for="ID" />

            <div class="form-group">
                <label asp-for="FirstMidName"
                    class="control-label"></label>
                <input asp-for="FirstMidName"
                    class="form-control" />
                <span asp-validation-for="FirstMidName"
                    class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="LastName"
                       class="control-label"></label>
                <input asp-for="LastName"
                       class="form-control" />
                <span asp-validation-for="LastName"
                      class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EnrollmentDate"
                       class="control-label"></label>
                <input asp-for="EnrollmentDate"
                       class="form-control" />
                <span asp-validation-for="EnrollmentDate"
                      class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar Alterações"
                       class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>

EFTest/EFTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EFTest</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EFTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EFTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentCourses" asp-action="Index">Matriculas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - EFTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>